* beer-me

Beer Me is a utility designed to quickly answer questions commonly brought forth in an on-call situation.

#+begin_src bash
  # example usage:
  beer-me ny order id '<some uuid>' # get an order by id from the ny db

  # get an order by id, while specifying the tax amount expected on the 'order_financial' table from the ca db
  beer-me ny order id '<some uuid>' "order_financial.tax_amount" 10

  beer-me ny order number=25436      # getting an order by number
#+end_src

** Usage
Usage follows the form =beer-me <environment> <resource> [filters]=

** Environment
The environment can be /exactly one of/ =ny=, =ca=, or =query=.

In the event of =ny= or =ca=, this determines which DB =psql= will be run against.

The =query= environment is a special case that will simply output the SQL to run,
allowing the user to manually paste the command wherever convenient.

** Resource
A =resource= can be thought of as either a row from a single table,
or a row from a series of tables joined together.

By default, the resources =order=, =product=, and =user= are defined,
and their template SQL is stored in =~/.config/beer-me/{order product user}.sql=.

The user can add any resources they wish, simply by adding a file named
=~/.config/beer-me/<resource>.sql=.

NOTE: it is very important that the terminating =;= is *not* included in the file,
or filter injection will /not/ work.

** Filters
Any arguments passed after the resource will be considered part of the =filters=.

=Filters= are expected to be in the form of whitespace-separated elements,
which will be parsed in pairs, and reformated into a where clause.

Double quotes and single quotes are both preserved, so a knowledge of the template
you are populating allows you to be cleve about how those filters are injected.
