* beer-me

Beer Me is a query-template management utility, designed to allow for quick and easy usage
of common queries, in various environments, with arbitrary injected filters.

** Usage
Usage follows the form =beer-me [environment] <resource> [filters]=

#+begin_src bash
  # example usage:
  beer-me local record -f "id = '<some uuid>'" # get an record by id from the 'local' environment/db

  # get an record by id, AND artist age expected on the 'artist' table from the  env/db
  beer-me local record -f "id '<some uuid>'" -f "artist.age = 20"

  beer-me record # output the query to get a record with no filters
#+end_src


** Environment
Environments are specified in the =~/.config/beer-me/.envlist= file, which is of the form:
#+begin_src
  ENV	psql postgres://user:password@localhost:54323/my_database -c"
#+end_src

Where the first column is the name of the environment, which will later be passed as the optional first argument.
Note that this column is case-insensitive, but is typically SCREAMING case for legibility.

The second column is the /command-stub/, where the query string generated by =beer-me=
is expected to be concatenated to the end.

Note: in the case of =psql=, for example, this means that the command must have a trailing =-c=.

The columns /must/ be tab separated.

** Resource
A =resource= can be thought of as either a row from a single table,
or a row from a series of tables joined together.

Resources are defined by including a ~template query~,  which is a file of the form
~/.config/beer-me/<resource-name>.sql.

#+begin_src sql
SELECT
    table_1.*,
    table_2.important_info AS table_2_info -- columns can be renamed
FROM table_1
JOIN table_2 ON table_1.id = table_2.table_1_id -- template queries can include joins
-- Note the lack of a WHERE clause, or of a terminating ";"
#+end_src sql

NOTE:
It is very important that the *neither* the terminating =;= *nor* any =WHERE= clauses
are included in the file, or filter injection will /not/ work.

** Filters
#+begin_src bash
  beer-me record -f "column_name = 'single quotes example'"
  beer-me record -f "\"column_name\" 'double quotes example'"
#+end_src
